### PR TITLE
examples: initial commit of the roundtripper example

### PR DESCRIPTION
**Pull request by rakyll**
DO NOT MERGE

### CODE REVIEW

**Comment by rakyll** [comment]
/cc @bmizerany

I was thinking about something as simple as this with ClientTrace support. We can mark stuff as they happen rather than doing it all at the finish time.

**Comment by bmizerany** [comment]
I started with marking spans as they happened, but there are some great benifits to defering until the end:

* A user can get access to detailed timing info we collected, rather than wrapping yet another ClientTrace around a ClientTrace. This is useful for logging requests after tracing them.
* We don't have all of the bookkeeping in RoundTrip for start/finish of each span. There may be a nice way to do this but I haven't found it.
* We can have a finish func for basic RTs, and another for detailed RTs (i.e. TTFB, ReadHeaders, ReadResponse, etc.) so users can pick how much detail they want.

**Comment by rakyll** [comment]
Ok, sounds good.

Btw, as I was working on this example, I realized that redirects are not handled well. req.Context() keeps returning the initial context set to the request on each RoundTrip. Brad suggested that we should better write a custom http.Client if we want to handle the redirects well.

Then we automatically can have traces like:

```
    google.com
|----------------|   www.google.com/
                 |-----------------------------------|
```

**Comment by bmizerany** [comment]
Good point. Noted.

**Comment by rakyll** [comment]
Closing due to inactivity.

**Pull request closed without merging**
